version: '3.3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: "postgres"
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres

  app:
    depends_on:
      - redis
      - db
    build: ./petpass-service
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:postgresql://db:5432/$DB_NAME",
              "spring.datasource.username" : "$DB_USER",
              "spring.datasource.password" : "$DB_PASSWORD",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "update",
              "spring.session.jdbc.initialize-schema":"always"
            }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: